monitor.bluez.rules = [
  {
    matches = [
      {
        ## This matches all Bluetooth devices.
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.default.rate = 44100
        bluez5.default.channels = 2
        bluez5.a2dp.ldac.quality = "sq"
      }
    }
  }
]
