monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.pci.*HiFi__(Headphones|HDMI[2-3])__sink"
      },
      {
        node.name = "~alsa_input.pci.*HiFi__Mic2__source"
      }
    ]
    actions = {
      update-props = {
         node.disabled = true
      }
    }
  }
]
