monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-MOTU_M4*"
      }
    ]
    actions = {
      update-props = {
        audio.position = "FL,FR,SL,SR"
      }
    }
  }
]
