[Service]
# Ensure a specific file or directory inside your mount point actually exists
ExecStartPre=/usr/bin/bash -c 'test -d /mnt/tnas/foma/Music'

# Throttling to prevent infinite spamming if a client aggressively retries
Restart=on-failure
RestartSec=5s
