copy_on_select yes

map ctrl+v       paste_from_clipboard
map ctrl+backspace send_text all \x17

map ctrl+tab                 send_text all gt
map ctrl+shift+tab           send_text all gT

confirm_os_window_close 0
