# Convolver sink
#
# Copy this file into a conf.d/ directory such as
# ~/.config/pipewire/filter-chain.conf.d/
#
# Adjust the paths to the convolver files to match your system
#
context.modules = [
    { name = libpipewire-module-filter-chain
        flags = [ nofail ]
        args = {
            node.description = "Daybreak"
            media.name       = "Daybreak"
            filter.graph = {
                nodes = [
                    {
                        type   = builtin
                        label  = param_eq
                        name   = leftrightEQ
                        config = {
                            filename1 = "/home/sergej/impulse/daybreak_eq_channel_balance_L.txt", filename2 = "/home/sergej/impulse/daybreak_eq_channel_balance_R.txt"
                        }
                    }

                    {
                        type   = builtin
                        label  = param_eq
                        name   = stereoEQ
                        config = {
                            filename = "/home/sergej/impulse/daybreak_eq_by_ear.txt"
                        }
                    }
                ]
                links = [
                    # input
                    { output = "leftrightEQ:Out 1"  input="stereoEQ:In 1"  }
                    { output = "leftrightEQ:Out 2"  input="stereoEQ:In 2"  }
                ]
                inputs  = [ "leftrightEQ:In 1" "leftrightEQ:In 2" ]
                outputs = [ "stereoEQ:Out 1" "stereoEQ:Out 2" ]
            }
            capture.props = {
                node.name      = "effect_input.equalizer"
                media.class    = Audio/Sink
                audio.channels = 2
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name      = "effect_output.equalizer"
                media.class    = Audio/Source
                node.passive   = true
                audio.channels = 2
                audio.position = [ FL FR ]
            }
        }
    }
]
