-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "preferred",
    position = "0x0",
    scale = "1.8",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "preferred",
    position = "-1920x-216",
    scale = "2",
    bitdepth = 10,
    cm = "dcip3",
})

hl.monitor({
    output = "DP-1",
    mode = "preferred",
    position = "-1920x-216",
    scale = "2",
    bitdepth = 10,
    cm = "dcip3",
})

-- monitor=DP-1,preferred,1600x0,1
hl.monitor({
    output = "DP-3",
    mode = "preferred",
    position = "-1920x-216",
    scale = "1",
})

hl.monitor({
    output = "DP-4",
    mode = "preferred",
    position = "-3000x-760",
    scale = "1",
    transform = 1,
})

hl.monitor({
    output = "DP-5",
    mode = "preferred",
    position = "-1920x-216",
    scale = "1",
})

hl.monitor({
    output = "DP-6",
    mode = "preferred",
    position = "-3000x-760",
    scale = "1",
    transform = 1,
})
