import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]
shell = "fish"

[window]
# dynamic_padding = true
padding = { x = 0, y = 0 }
dimensions = { columns = 80, lines = 24 }
# decorations = "None"
# startup_mode = "Maximized"
opacity = 1

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

# [mouse]
# bindings = [
# { mouse = "Right", action = "Paste" },
# ]

[keyboard]
bindings = [
{ key = "V", mods = "Control", action = "Paste" },
# { key = "Backspace", mods = "Control", chars = "\u001b\u007f" },
{ key = "Delete", mods = "Control", chars = "\u001bd" },
]

# Normal colors
[colors.normal]
black = '#2c2e3a' # surface1
red = '#cf446b' # red
green = '#5fa659' # green
yellow = '#d9a534' # yellow
blue = '#4071bf' # blue
magenta = '#c456a7' # pink
cyan = '#59a699' # teal
white = '#5366ac' # subtext1

# Dim colors
[colors.dim]
black = '#2c2e3a' # surface1
red = '#cf446b' # red
green = '#5fa659' # green
yellow = '#d9a534' # yellow
blue = '#4071bf' # blue
magenta = '#c456a7' # pink
cyan = '#59a699' # teal
white = '#5366ac' # subtext1
