#!/usr/bin/bash
swaylock \
--image "~/Pictures/wallpaper/cirno_3.jpg" \
--indicator \
--clock \
--font "Noto Sans Light" \
--hide-keyboard-layout \
--ring-wrong-color 00000000  \
--ring-clear-color 00000000 \
--ring-ver-color 00000000 \
--inside-wrong-color 1E1E2E60  \
--inside-clear-color 1E1E2E60 \
--inside-ver-color 1E1E2E60 \
--text-color  ffffff \
--text-clear-color  a6e3a1 \
--text-ver-color  89b4fa \
--text-wrong-color  f38ba8 \
--indicator-radius 200 \
--indicator-thickness 3 \
--effect-vignette 0.4:0.4 \
--ring-color 00161925 \
--key-hl-color 89b4fa \
--line-color ffffff80 \
--line-clear-color ffffff80 \
--line-ver-color ffffff80 \
--line-wrong-color ffffff80 \
--inside-color 1E1E2E40 \
--separator-color 00000000 \
--fade-in 0.5 &

# --effect-blur 10x2 \
# sleep 2; ~/.config/hypr/scripts/screenshot_full
