#!/usr/bin/bash

cat <<EOF > ~/.config/hypr/background.conf
background {
    monitor =
    path = $(~/.scripts/wallpaper.sh query)
    blur_passes = 2
    blur_size = 5
}
EOF

hyprctl switchxkblayout current 0 ; pgrep hyprlock || hyprlock
