#!/usr/bin/bash
# Script by PROxZIMA from https://github.com/PROxZIMA/.dotfiles/tree/master
IMG=~/Pictures/Screenshots/$(date +'Screenshot_%Y-%m-%d_%H-%M-%S.png') && grim -g "$(slurp -c cba6f788 -b 00000055 -w 0)" $IMG && wl-copy < $IMG && notify-send -e -h boolean:SWAYNC_BYPASS_DND:true -u low "Screenshot" "Saved & Copied";
